default: &default
  adapter: mysql2
  host: 127.0.0.1
  pool: 2
  username: <%= ENV['DB_USER']  %>
  password: <%= ENV['DB_PSWD'] %>

development:
  <<: *default
  database: turing

test:
  <<: *default
  database: turing_test
